---
- name: containerd | Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libseccomp2
    - ethtool

- name: containerd | Download files
  include_role:
    name: download
  vars:
    download_container: false

- name: containerd | Unpack release tarball
  unarchive:
    src: "{{ local_release_dir }}/cri-containerd-cni-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: /
    remote_src: true
    creates: /etc/systemd/system/containerd.service

- name: containerd | Start containerd
  systemd:
    name: containerd
    state: started
